/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sqlancer_jni_UtilSHM */

#ifndef _Included_sqlancer_jni_UtilSHM
#define _Included_sqlancer_jni_UtilSHM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sqlancer_jni_UtilSHM
 * Method:    initBarrier
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sqlancer_jni_UtilSHM_initBarrier
  (JNIEnv *, jobject, jint);

/*
 * Class:     sqlancer_jni_UtilSHM
 * Method:    updateBarrier
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_sqlancer_jni_UtilSHM_updateBarrier
  (JNIEnv *, jobject, jint);

/*
 * Class:     sqlancer_jni_UtilSHM
 * Method:    initLoc
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_sqlancer_jni_UtilSHM_initLoc
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
